# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.bill_validation_response import BillValidationResponse

class TestBillValidationResponse(unittest.TestCase):
    """BillValidationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillValidationResponse:
        """Test BillValidationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillValidationResponse`
        """
        model = BillValidationResponse()
        if include_optional:
            return BillValidationResponse(
                status = True,
                code = 0,
                message = 'success',
                data = jenga_client.models.bill_validation_response_data.BillValidationResponse_data(
                    amount = '1000.0', 
                    customer_ref_number = '101704', 
                    name = 'John Doe', 
                    bill_status = 'true', 
                    message = 'SUCCESS', 
                    created_on = 'Fri Jun 24 11:04:14 EAT 2022', 
                    amount_currency = 'KES', 
                    status = True, )
            )
        else:
            return BillValidationResponse(
        )
        """

    def testBillValidationResponse(self):
        """Test BillValidationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
