# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_api_checkout_api_v1_create_payment_link_post(self) -> None:
        """Test case for api_checkout_api_v1_create_payment_link_post

        Create Payment Link
        """
        pass

    def test_api_checkout_mpesa_stk_push_v30_init_post(self) -> None:
        """Test case for api_checkout_mpesa_stk_push_v30_init_post

        Initiate M-Pesa STK Push
        """
        pass

    def test_api_checkout_mpesa_stk_push_v30_status_order_reference_get(self) -> None:
        """Test case for api_checkout_mpesa_stk_push_v30_status_order_reference_get

        Query M-Pesa STK Push Order Status
        """
        pass

    def test_authentication_api_v3_authenticate_merchant_post(self) -> None:
        """Test case for authentication_api_v3_authenticate_merchant_post

        Authenticate merchant
        """
        pass

    def test_v3_apis_payment_api_v30_stkussdpush_initiate_post(self) -> None:
        """Test case for v3_apis_payment_api_v30_stkussdpush_initiate_post

        Initiate Equitel STK/USSD Push
        """
        pass

    def test_v3_apis_transaction_api_v30_billers_get(self) -> None:
        """Test case for v3_apis_transaction_api_v30_billers_get

        Get All Billers
        """
        pass

    def test_v3_apis_transaction_api_v30_bills_pay_post(self) -> None:
        """Test case for v3_apis_transaction_api_v30_bills_pay_post

        Initiate bill payment
        """
        pass

    def test_v3_apis_transaction_api_v30_bills_validation_post(self) -> None:
        """Test case for v3_apis_transaction_api_v30_bills_validation_post

        Validate bill
        """
        pass

    def test_v3_apis_transaction_api_v30_merchants_get(self) -> None:
        """Test case for v3_apis_transaction_api_v30_merchants_get

        Get All EazzyPay Merchants
        """
        pass

    def test_v3_apis_transaction_api_v30_remittance_internal_bank_transfer_imt_post(self) -> None:
        """Test case for v3_apis_transaction_api_v30_remittance_internal_bank_transfer_imt_post

        IMT Within Equity Bank
        """
        pass

    def test_v3_apis_transaction_api_v30_transaction_transaction_id_get(self) -> None:
        """Test case for v3_apis_transaction_api_v30_transaction_transaction_id_get

        Get Transaction Details
        """
        pass


if __name__ == '__main__':
    unittest.main()
