# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.bill_payment_request import BillPaymentRequest

class TestBillPaymentRequest(unittest.TestCase):
    """BillPaymentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillPaymentRequest:
        """Test BillPaymentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillPaymentRequest`
        """
        model = BillPaymentRequest()
        if include_optional:
            return BillPaymentRequest(
                biller = jenga_client.models.bill_payment_request_biller.BillPaymentRequest_biller(
                    biller_code = '320320', 
                    country_code = 'KE', ),
                bill = jenga_client.models.bill_payment_request_bill.BillPaymentRequest_bill(
                    reference = '10170476767676', 
                    amount = '111.00', 
                    currency = 'KES', ),
                payer = jenga_client.models.bill_payment_request_payer.BillPaymentRequest_payer(
                    name = 'A. N Other', 
                    account = '101704', 
                    reference = '123451000002', 
                    mobile_number = '0764555320', ),
                partner_id = '0020100014605',
                remarks = 'These are just some remarks'
            )
        else:
            return BillPaymentRequest(
                biller = jenga_client.models.bill_payment_request_biller.BillPaymentRequest_biller(
                    biller_code = '320320', 
                    country_code = 'KE', ),
                bill = jenga_client.models.bill_payment_request_bill.BillPaymentRequest_bill(
                    reference = '10170476767676', 
                    amount = '111.00', 
                    currency = 'KES', ),
                payer = jenga_client.models.bill_payment_request_payer.BillPaymentRequest_payer(
                    name = 'A. N Other', 
                    account = '101704', 
                    reference = '123451000002', 
                    mobile_number = '0764555320', ),
                partner_id = '0020100014605',
        )
        """

    def testBillPaymentRequest(self):
        """Test BillPaymentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
