# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.eazzy_pay_merchants_response import EazzyPayMerchantsResponse

class TestEazzyPayMerchantsResponse(unittest.TestCase):
    """EazzyPayMerchantsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EazzyPayMerchantsResponse:
        """Test EazzyPayMerchantsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EazzyPayMerchantsResponse`
        """
        model = EazzyPayMerchantsResponse()
        if include_optional:
            return EazzyPayMerchantsResponse(
                merchants = [
                    jenga_client.models.eazzy_pay_merchant.EazzyPayMerchant(
                        name = 'Nakumatt', 
                        tillnumber = '0766002221', 
                        outlets = [
                            jenga_client.models.eazzy_pay_merchant_outlets_inner.EazzyPayMerchant_outlets_inner(
                                name = 'Nakumatt Presitige', 
                                tillnumber = '0766002201', )
                            ], )
                    ]
            )
        else:
            return EazzyPayMerchantsResponse(
        )
        """

    def testEazzyPayMerchantsResponse(self):
        """Test EazzyPayMerchantsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
