# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.payment_link_request_customers_inner import PaymentLinkRequestCustomersInner

class TestPaymentLinkRequestCustomersInner(unittest.TestCase):
    """PaymentLinkRequestCustomersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentLinkRequestCustomersInner:
        """Test PaymentLinkRequestCustomersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentLinkRequestCustomersInner`
        """
        model = PaymentLinkRequestCustomersInner()
        if include_optional:
            return PaymentLinkRequestCustomersInner(
                first_name = 'John',
                last_name = 'Doe',
                email = 'johndoe902@gmail.com',
                phone_number = '254764848636',
                first_address = '',
                country_code = 'KE',
                postal_or_zip_code = '00100',
                customer_external_ref = '575657788779'
            )
        else:
            return PaymentLinkRequestCustomersInner(
                first_name = 'John',
                last_name = 'Doe',
                email = 'johndoe902@gmail.com',
                country_code = 'KE',
        )
        """

    def testPaymentLinkRequestCustomersInner(self):
        """Test PaymentLinkRequestCustomersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
