# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.bill_payment_request_biller import BillPaymentRequestBiller

class TestBillPaymentRequestBiller(unittest.TestCase):
    """BillPaymentRequestBiller unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillPaymentRequestBiller:
        """Test BillPaymentRequestBiller
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillPaymentRequestBiller`
        """
        model = BillPaymentRequestBiller()
        if include_optional:
            return BillPaymentRequestBiller(
                biller_code = '320320',
                country_code = 'KE'
            )
        else:
            return BillPaymentRequestBiller(
                biller_code = '320320',
                country_code = 'KE',
        )
        """

    def testBillPaymentRequestBiller(self):
        """Test BillPaymentRequestBiller"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
