# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.m_pesa_stk_push_request_customer import MPesaStkPushRequestCustomer

class TestMPesaStkPushRequestCustomer(unittest.TestCase):
    """MPesaStkPushRequestCustomer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MPesaStkPushRequestCustomer:
        """Test MPesaStkPushRequestCustomer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MPesaStkPushRequestCustomer`
        """
        model = MPesaStkPushRequestCustomer()
        if include_optional:
            return MPesaStkPushRequestCustomer(
                name = 'John Doe',
                email = 'xyx2@gmail.com',
                phone_number = '0722000111',
                identity_number = '0000000',
                first_address = '',
                second_address = ''
            )
        else:
            return MPesaStkPushRequestCustomer(
                name = 'John Doe',
                email = 'xyx2@gmail.com',
                phone_number = '0722000111',
                identity_number = '0000000',
        )
        """

    def testMPesaStkPushRequestCustomer(self):
        """Test MPesaStkPushRequestCustomer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
