# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.payment_link_response_data import PaymentLinkResponseData

class TestPaymentLinkResponseData(unittest.TestCase):
    """PaymentLinkResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentLinkResponseData:
        """Test PaymentLinkResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentLinkResponseData`
        """
        model = PaymentLinkResponseData()
        if include_optional:
            return PaymentLinkResponseData(
                date_created = 1709277210697,
                payment_link_ref = '456175577507808',
                external_ref = '565657788779',
                status = jenga_client.models.payment_link_response_data_status.PaymentLinkResponse_data_status(
                    code = 'PEND', 
                    name = 'Pending', )
            )
        else:
            return PaymentLinkResponseData(
        )
        """

    def testPaymentLinkResponseData(self):
        """Test PaymentLinkResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
