# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.bill_payment_response import BillPaymentResponse

class TestBillPaymentResponse(unittest.TestCase):
    """BillPaymentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillPaymentResponse:
        """Test BillPaymentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillPaymentResponse`
        """
        model = BillPaymentResponse()
        if include_optional:
            return BillPaymentResponse(
                status = True,
                code = 0,
                message = 'success',
                reference = '10170476767676',
                data = jenga_client.models.bill_payment_response_data.BillPaymentResponse_data(
                    transaction_id = '123451000002', 
                    status = 'SUCCESS', )
            )
        else:
            return BillPaymentResponse(
        )
        """

    def testBillPaymentResponse(self):
        """Test BillPaymentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
