# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.m_pesa_transaction_status_data_invoices_inner import MPesaTransactionStatusDataInvoicesInner

class TestMPesaTransactionStatusDataInvoicesInner(unittest.TestCase):
    """MPesaTransactionStatusDataInvoicesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MPesaTransactionStatusDataInvoicesInner:
        """Test MPesaTransactionStatusDataInvoicesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MPesaTransactionStatusDataInvoicesInner`
        """
        model = MPesaTransactionStatusDataInvoicesInner()
        if include_optional:
            return MPesaTransactionStatusDataInvoicesInner(
                amount = 100.0,
                amount_debited = 100.0,
                charge = 0.0,
                invoice_status = 'Expired',
                order_reference = 'ORD1748939052F6DD4B',
                external_reference = '',
                created_on = '2025-06-03 11:26:22.347',
                completed_on = ''
            )
        else:
            return MPesaTransactionStatusDataInvoicesInner(
        )
        """

    def testMPesaTransactionStatusDataInvoicesInner(self):
        """Test MPesaTransactionStatusDataInvoicesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
