# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.authentication_request import AuthenticationRequest

class TestAuthenticationRequest(unittest.TestCase):
    """AuthenticationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthenticationRequest:
        """Test AuthenticationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthenticationRequest`
        """
        model = AuthenticationRequest()
        if include_optional:
            return AuthenticationRequest(
                merchant_code = '123456',
                consumer_secret = 'secret123'
            )
        else:
            return AuthenticationRequest(
                merchant_code = '123456',
                consumer_secret = 'secret123',
        )
        """

    def testAuthenticationRequest(self):
        """Test AuthenticationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
