# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.equitel_push_request import EquitelPushRequest

class TestEquitelPushRequest(unittest.TestCase):
    """EquitelPushRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EquitelPushRequest:
        """Test EquitelPushRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EquitelPushRequest`
        """
        model = EquitelPushRequest()
        if include_optional:
            return EquitelPushRequest(
                merchant = jenga_client.models.equitel_push_request_merchant.EquitelPushRequest_merchant(
                    country_code = 'KE', 
                    account_number = '0170194290581', 
                    name = 'Sportify Ltd', ),
                payment = jenga_client.models.equitel_push_request_payment.EquitelPushRequest_payment(
                    ref = 'MPS3883889822982', 
                    mobile_number = '254764555291', 
                    telco = 'Equitel', 
                    amount = '5.00', 
                    date = '2024-08-13', 
                    call_back_url = 'https://webhook.site/6173e296-a2b0-4fb5-a06e-bfbb2e352e30', 
                    push_type = 'STK', )
            )
        else:
            return EquitelPushRequest(
                merchant = jenga_client.models.equitel_push_request_merchant.EquitelPushRequest_merchant(
                    country_code = 'KE', 
                    account_number = '0170194290581', 
                    name = 'Sportify Ltd', ),
                payment = jenga_client.models.equitel_push_request_payment.EquitelPushRequest_payment(
                    ref = 'MPS3883889822982', 
                    mobile_number = '254764555291', 
                    telco = 'Equitel', 
                    amount = '5.00', 
                    date = '2024-08-13', 
                    call_back_url = 'https://webhook.site/6173e296-a2b0-4fb5-a06e-bfbb2e352e30', 
                    push_type = 'STK', ),
        )
        """

    def testEquitelPushRequest(self):
        """Test EquitelPushRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
