# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.eazzy_pay_merchant_outlets_inner import EazzyPayMerchantOutletsInner

class TestEazzyPayMerchantOutletsInner(unittest.TestCase):
    """EazzyPayMerchantOutletsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EazzyPayMerchantOutletsInner:
        """Test EazzyPayMerchantOutletsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EazzyPayMerchantOutletsInner`
        """
        model = EazzyPayMerchantOutletsInner()
        if include_optional:
            return EazzyPayMerchantOutletsInner(
                name = 'Nakumatt Presitige',
                tillnumber = '0766002201'
            )
        else:
            return EazzyPayMerchantOutletsInner(
        )
        """

    def testEazzyPayMerchantOutletsInner(self):
        """Test EazzyPayMerchantOutletsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
