# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.imt_within_equity_request_destination import IMTWithinEquityRequestDestination

class TestIMTWithinEquityRequestDestination(unittest.TestCase):
    """IMTWithinEquityRequestDestination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IMTWithinEquityRequestDestination:
        """Test IMTWithinEquityRequestDestination
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IMTWithinEquityRequestDestination`
        """
        model = IMTWithinEquityRequestDestination()
        if include_optional:
            return IMTWithinEquityRequestDestination(
                type = 'bank',
                country_code = 'KE',
                name = 'A N.Other',
                bank_code = '03',
                account_number = '101080530003',
                mobile_number = '0763123456',
                document_type = 'NationalId',
                document_number = '123456',
                email = 'recipient.name@example.com',
                address = 'Nairobi'
            )
        else:
            return IMTWithinEquityRequestDestination(
                type = 'bank',
                country_code = 'KE',
                name = 'A N.Other',
                bank_code = '03',
                account_number = '101080530003',
                mobile_number = '0763123456',
                document_type = 'NationalId',
                document_number = '123456',
        )
        """

    def testIMTWithinEquityRequestDestination(self):
        """Test IMTWithinEquityRequestDestination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
