# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.equitel_callback_response import EquitelCallbackResponse

class TestEquitelCallbackResponse(unittest.TestCase):
    """EquitelCallbackResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EquitelCallbackResponse:
        """Test EquitelCallbackResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EquitelCallbackResponse`
        """
        model = EquitelCallbackResponse()
        if include_optional:
            return EquitelCallbackResponse(
                status = True,
                code = 3,
                message = 'Successful',
                transaction_reference = 'MPS3883889822982',
                telco_reference = 'MPS3883889822982',
                mobile_number = '254764555291',
                debited_amount = 5,
                request_amount = 5,
                charge = 1,
                currency = 'KES',
                telco = 'Equitel'
            )
        else:
            return EquitelCallbackResponse(
        )
        """

    def testEquitelCallbackResponse(self):
        """Test EquitelCallbackResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
