# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.payment_link_response import PaymentLinkResponse

class TestPaymentLinkResponse(unittest.TestCase):
    """PaymentLinkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentLinkResponse:
        """Test PaymentLinkResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentLinkResponse`
        """
        model = PaymentLinkResponse()
        if include_optional:
            return PaymentLinkResponse(
                status = True,
                code = 200,
                message = 'Payment link successfully generated',
                metadata = None,
                data = jenga_client.models.payment_link_response_data.PaymentLinkResponse_data(
                    date_created = 1709277210697, 
                    payment_link_ref = '456175577507808', 
                    external_ref = '565657788779', 
                    status = jenga_client.models.payment_link_response_data_status.PaymentLinkResponse_data_status(
                        code = 'PEND', 
                        name = 'Pending', ), )
            )
        else:
            return PaymentLinkResponse(
        )
        """

    def testPaymentLinkResponse(self):
        """Test PaymentLinkResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
