# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.biller import Biller

class TestBiller(unittest.TestCase):
    """Biller unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Biller:
        """Test Biller
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Biller`
        """
        model = Biller()
        if include_optional:
            return Biller(
                biller_code = '320320',
                biller_name = 'KPLC',
                country_code = 'KE',
                category = 'UTILITY'
            )
        else:
            return Biller(
        )
        """

    def testBiller(self):
        """Test Biller"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
