# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.imt_within_equity_request_sender import IMTWithinEquityRequestSender

class TestIMTWithinEquityRequestSender(unittest.TestCase):
    """IMTWithinEquityRequestSender unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IMTWithinEquityRequestSender:
        """Test IMTWithinEquityRequestSender
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IMTWithinEquityRequestSender`
        """
        model = IMTWithinEquityRequestSender()
        if include_optional:
            return IMTWithinEquityRequestSender(
                name = 'Sender Name',
                document_type = 'NationalId',
                document_number = '12345',
                country_code = 'KE',
                mobile_number = '0763000000',
                email = 'sender.name@example.com',
                address = 'UAE'
            )
        else:
            return IMTWithinEquityRequestSender(
                name = 'Sender Name',
                document_type = 'NationalId',
                document_number = '12345',
                country_code = 'KE',
                mobile_number = '0763000000',
                email = 'sender.name@example.com',
        )
        """

    def testIMTWithinEquityRequestSender(self):
        """Test IMTWithinEquityRequestSender"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
