# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.imt_within_equity_request_transfer import IMTWithinEquityRequestTransfer

class TestIMTWithinEquityRequestTransfer(unittest.TestCase):
    """IMTWithinEquityRequestTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IMTWithinEquityRequestTransfer:
        """Test IMTWithinEquityRequestTransfer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IMTWithinEquityRequestTransfer`
        """
        model = IMTWithinEquityRequestTransfer()
        if include_optional:
            return IMTWithinEquityRequestTransfer(
                type = 'InternalFundsTransfer',
                amount = '1000',
                currency_code = 'KES',
                reference = '123456789012',
                var_date = '2018-08-18',
                description = 'some remarks here'
            )
        else:
            return IMTWithinEquityRequestTransfer(
                type = 'InternalFundsTransfer',
                amount = '1000',
                currency_code = 'KES',
                reference = '123456789012',
                var_date = '2018-08-18',
        )
        """

    def testIMTWithinEquityRequestTransfer(self):
        """Test IMTWithinEquityRequestTransfer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
