# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.bill_payment_request_payer import BillPaymentRequestPayer

class TestBillPaymentRequestPayer(unittest.TestCase):
    """BillPaymentRequestPayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillPaymentRequestPayer:
        """Test BillPaymentRequestPayer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillPaymentRequestPayer`
        """
        model = BillPaymentRequestPayer()
        if include_optional:
            return BillPaymentRequestPayer(
                name = 'A. N Other',
                account = '101704',
                reference = '123451000002',
                mobile_number = '0764555320'
            )
        else:
            return BillPaymentRequestPayer(
                name = 'A. N Other',
                account = '101704',
                reference = '123451000002',
                mobile_number = '0764555320',
        )
        """

    def testBillPaymentRequestPayer(self):
        """Test BillPaymentRequestPayer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
