# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.m_pesa_callback_response_transaction import MPesaCallbackResponseTransaction

class TestMPesaCallbackResponseTransaction(unittest.TestCase):
    """MPesaCallbackResponseTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MPesaCallbackResponseTransaction:
        """Test MPesaCallbackResponseTransaction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MPesaCallbackResponseTransaction`
        """
        model = MPesaCallbackResponseTransaction()
        if include_optional:
            return MPesaCallbackResponseTransaction(
                var_date = '2024-08-09 16:22:50',
                reference = 'SH90HU7FO2',
                payment_mode = 'MPESA',
                amount = 2,
                currency = 'KES',
                service_charge = 1,
                bill_number = 'INVDBU',
                served_by = 'JENGA',
                additional_info = 'MPESA',
                order_amount = 2,
                order_currency = 'KES',
                status = 'SUCCESS',
                remarks = 'ED990222'
            )
        else:
            return MPesaCallbackResponseTransaction(
        )
        """

    def testMPesaCallbackResponseTransaction(self):
        """Test MPesaCallbackResponseTransaction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
