# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.imt_within_equity_request_source import IMTWithinEquityRequestSource

class TestIMTWithinEquityRequestSource(unittest.TestCase):
    """IMTWithinEquityRequestSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IMTWithinEquityRequestSource:
        """Test IMTWithinEquityRequestSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IMTWithinEquityRequestSource`
        """
        model = IMTWithinEquityRequestSource()
        if include_optional:
            return IMTWithinEquityRequestSource(
                country_code = 'KE',
                name = 'Merchant name',
                account_number = '0011547896523'
            )
        else:
            return IMTWithinEquityRequestSource(
                country_code = 'KE',
                name = 'Merchant name',
                account_number = '0011547896523',
        )
        """

    def testIMTWithinEquityRequestSource(self):
        """Test IMTWithinEquityRequestSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
