# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.equitel_push_response import EquitelPushResponse

class TestEquitelPushResponse(unittest.TestCase):
    """EquitelPushResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EquitelPushResponse:
        """Test EquitelPushResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EquitelPushResponse`
        """
        model = EquitelPushResponse()
        if include_optional:
            return EquitelPushResponse(
                status = True,
                code = -1,
                message = 'Transaction has been successfully acknowledged, await final transaction status on callback',
                reference = 'MPS3883889822982',
                transaction_id = 'MPS3883889822982'
            )
        else:
            return EquitelPushResponse(
        )
        """

    def testEquitelPushResponse(self):
        """Test EquitelPushResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
