# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.m_pesa_callback_response import MPesaCallbackResponse

class TestMPesaCallbackResponse(unittest.TestCase):
    """MPesaCallbackResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MPesaCallbackResponse:
        """Test MPesaCallbackResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MPesaCallbackResponse`
        """
        model = MPesaCallbackResponse()
        if include_optional:
            return MPesaCallbackResponse(
                callback_type = 'IPN',
                customer = jenga_client.models.m_pesa_callback_response_customer.MPesaCallbackResponse_customer(
                    name = 'John Doe', 
                    mobile_number = '0722000000', 
                    reference = 'OR28922980077', ),
                transaction = jenga_client.models.m_pesa_callback_response_transaction.MPesaCallbackResponse_transaction(
                    date = '2024-08-09 16:22:50', 
                    reference = 'SH90HU7FO2', 
                    payment_mode = 'MPESA', 
                    amount = 2, 
                    currency = 'KES', 
                    service_charge = 1, 
                    bill_number = 'INVDBU', 
                    served_by = 'JENGA', 
                    additional_info = 'MPESA', 
                    order_amount = 2, 
                    order_currency = 'KES', 
                    status = 'SUCCESS', 
                    remarks = 'ED990222', ),
                bank = jenga_client.models.m_pesa_callback_response_bank.MPesaCallbackResponse_bank(
                    reference = 'NONE', 
                    transaction_type = 'C', 
                    account = 'NONE', )
            )
        else:
            return MPesaCallbackResponse(
        )
        """

    def testMPesaCallbackResponse(self):
        """Test MPesaCallbackResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
