# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.authentication_response import AuthenticationResponse

class TestAuthenticationResponse(unittest.TestCase):
    """AuthenticationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthenticationResponse:
        """Test AuthenticationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthenticationResponse`
        """
        model = AuthenticationResponse()
        if include_optional:
            return AuthenticationResponse(
                access_token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
                expires_in = '2024-03-20T10:00:00Z',
                issued_at = '2024-03-20T09:00:00Z',
                token_type = 'Bearer',
                refresh_token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
            )
        else:
            return AuthenticationResponse(
        )
        """

    def testAuthenticationResponse(self):
        """Test AuthenticationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
