# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.transaction_details_response import TransactionDetailsResponse

class TestTransactionDetailsResponse(unittest.TestCase):
    """TransactionDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionDetailsResponse:
        """Test TransactionDetailsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionDetailsResponse`
        """
        model = TransactionDetailsResponse()
        if include_optional:
            return TransactionDetailsResponse(
                status = True,
                code = '0',
                message = 'Transaction details retrieved successfully',
                data = jenga_client.models.transaction_details_response_data.TransactionDetailsResponse_data(
                    transaction_id = 'TR123456789', 
                    amount = 1000.0, 
                    currency = 'KES', 
                    status = 'SUCCESS', 
                    state_code = 2, 
                    date = '2024-02-20T10:00:00Z', )
            )
        else:
            return TransactionDetailsResponse(
        )
        """

    def testTransactionDetailsResponse(self):
        """Test TransactionDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
