# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.bill_payment_response_data import BillPaymentResponseData

class TestBillPaymentResponseData(unittest.TestCase):
    """BillPaymentResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillPaymentResponseData:
        """Test BillPaymentResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillPaymentResponseData`
        """
        model = BillPaymentResponseData()
        if include_optional:
            return BillPaymentResponseData(
                transaction_id = '123451000002',
                status = 'SUCCESS'
            )
        else:
            return BillPaymentResponseData(
        )
        """

    def testBillPaymentResponseData(self):
        """Test BillPaymentResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
