# coding: utf-8

"""
    Jenga API

    API for Jenga payment processing and transaction management

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jenga_client.models.m_pesa_stk_push_request_order import MPesaStkPushRequestOrder

class TestMPesaStkPushRequestOrder(unittest.TestCase):
    """MPesaStkPushRequestOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MPesaStkPushRequestOrder:
        """Test MPesaStkPushRequestOrder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MPesaStkPushRequestOrder`
        """
        model = MPesaStkPushRequestOrder()
        if include_optional:
            return MPesaStkPushRequestOrder(
                order_reference = 'OR28922980077',
                order_amount = 2,
                order_currency = 'KES',
                source = 'APICHECKOUT',
                country_code = 'KE',
                description = 'Purchase'
            )
        else:
            return MPesaStkPushRequestOrder(
                order_reference = 'OR28922980077',
                order_amount = 2,
                order_currency = 'KES',
                source = 'APICHECKOUT',
                country_code = 'KE',
                description = 'Purchase',
        )
        """

    def testMPesaStkPushRequestOrder(self):
        """Test MPesaStkPushRequestOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
